server:
  port: 8080
spring:
  datasource:
    username: postgres
    password: 28072004
    url: jdbc:postgresql://localhost:5432/springBoot-db
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
management:
  endpoints:
    web:
      exposure:
        include: '*'
