server:
  port: 8081
spring:
  datasource:
    username: postgres
    password: 28072004
    url: jdbc:postgresql://localhost:5432/springBoot-db
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: '*'
